#!/usr/bin/env python
"""Publish the model findings as a committed, readable Markdown report.

The Phase 3 artifacts live in `data/`, which is gitignored because it also holds
`training_data.csv` — real production tonnages, and the mirror is public. That
protects the data but hides the CONCLUSIONS from anyone reading the repo.

This script extracts only derived statistics (coefficients, p-values, VIF,
cross-validation scores, residual flags) into `MODEL_FINDINGS.md`, which IS
committed. No tonnages, no route-level volumes, no per-contractor production —
only what a reviewer needs to judge the model.

    python scripts/publish_findings.py
"""
from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(BASE, "data")
OUT = os.path.join(BASE, "MODEL_FINDINGS.md")

# Human-readable names for the operational levers. Route and contractor dummies
# are summarised rather than listed: naming every route with its coefficient
# would edge back toward publishing the operation's shape.
FRIENDLY = {
    "trucks_dt": "Fleet on this route (trucks)",
    "rainfall_mm": "Rainfall (mm)",
    "payload_t": "Payload per trip (t)",
    "weighbridges_open": "Weighbridges open",
    "trucks_per_path": "Total trucks sharing the road (congestion)",
    "rain_x_distance": "Rain x haul distance (interaction)",
    "rain_x_trucks": "Rain x fleet size (interaction)",
    "is_weekend": "Weekend shift",
    "rainfall_missing": "Rainfall reading missing (gauge outage)",
}


def _load(name, default=None):
    try:
        with open(os.path.join(DATA, name), encoding="utf-8") as fh:
            return json.load(fh)
    except Exception:                                          # noqa: BLE001
        return default


def _stars(p):
    if p is None:
        return ""
    return "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""


def build() -> str:
    sig = _load("feature_significance.json") or {}
    cmp_ = _load("model_comparison.json") or {}
    val = _load("validation_results.json") or {}
    res = _load("residual_diagnostics.json") or {}
    meta = _load("model_metadata.json") or {}
    tmeta = _load("training_metadata.json") or {}
    if not sig:
        return ""

    coefs = sig.get("coefficients", {})
    mean_r2 = cmp_.get("mean_r2", {})
    L = []
    A = L.append

    A("# WBN FMS Simulator — Model Findings")
    A("")
    A("*Generated by `scripts/publish_findings.py` from the artifacts in "
      "`data/` (gitignored). Regenerate after any retrain.*")
    A("")
    A("Derived statistics only — no tonnages or route-level production volumes.")
    A("")
    A("| | |")
    A("|---|---|")
    A("| Generated | %s |" % datetime.now(timezone.utc).isoformat(timespec="seconds"))
    A("| Training rows | %s |" % f"{sig.get('n_rows', 0):,}")
    A("| Date range | %s |" % " to ".join(tmeta.get("date_range", ["?", "?"])))
    A("| Data source | %s |" % tmeta.get("source", "unknown"))
    A("| Target | `trips_per_dt_per_shift` (trips per truck per shift) |")
    A("")

    # ── headline ────────────────────────────────────────────────────────────
    A("## Headline: no fitted model beats a lookup table")
    A("")
    A("Scored under **rolling-origin (walk-forward) cross-validation** — train on")
    A("the past, test on the next block, never shuffle. All models see identical folds.")
    A("")
    A("| Model | mean CV R² | |")
    A("|---|---|---|")
    for k in ("group_mean_baseline", "ols", "random_forest"):
        if k in mean_r2:
            label = {"group_mean_baseline": "Group-mean lookup (per route/contractor/shift)",
                     "ols": "OLS regression", "random_forest": "RandomForest"}[k]
            chosen = (k == cmp_.get("selected_model"))
            A("| %s | %s | %s |" % (
                ("**%s**" % label) if chosen else label,
                ("**%.3f**" % mean_r2[k]) if chosen else ("%.3f" % mean_r2[k]),
                "**selected**" if chosen else ""))
    A("")
    A("**Selected: `%s`** — %s" % (cmp_.get("selected_model", "?"),
                                   cmp_.get("selection_rationale", "")))
    A("")
    A("> A single chronological split reports much higher numbers (OLS ~0.56, RF ~0.59)")
    A("> because it scores one held-out block. The cross-validated figures above are")
    A("> what survived being tested on months the model had never seen.")
    A("")

    # ── per fold ────────────────────────────────────────────────────────────
    folds = (val.get("ols") or {}).get("folds", [])
    if folds:
        A("### OLS per fold")
        A("")
        A("| Test period | Train rows | Test rows | R² | MAE | MAPE | Rain varies? |")
        A("|---|---|---|---|---|---|---|")
        for f in folds:
            if f.get("r2") is None:
                continue
            A("| %s | %s | %s | %.3f | %.3f | %.1f%% | %s |" % (
                f.get("test_period"), f"{f.get('train_rows', 0):,}",
                f"{f.get('test_rows', 0):,}", f["r2"], f.get("mae", 0),
                f.get("mape", 0), "no" if f.get("test_rain_all_zero") else "yes"))
        A("")
        A("Folds where rain does not vary **cannot validate any rainfall coefficient** —")
        A("the gauges stopped reporting on 2026-04-06, so rain is constant there.")
        A("")

    # ── coefficients ────────────────────────────────────────────────────────
    A("## What actually moves productivity")
    A("")
    A("OLS coefficients in **trips per truck per shift**. `***` p<0.001, `**` p<0.01, `*` p<0.05.")
    A("")
    A("| Factor | Effect | 95% CI | p | |")
    A("|---|---|---|---|---|")
    for key, label in FRIENDLY.items():
        c = coefs.get(key)
        if not c:
            continue
        A("| %s | %+.5f | [%+.4f, %+.4f] | %.3f | %s |" % (
            label, c["coef"], c["ci_low"], c["ci_high"], c["p_value"],
            _stars(c["p_value"])))
    A("")
    n_route = sum(1 for k in coefs if k.startswith("route_"))
    n_contr = sum(1 for k in coefs if k.startswith("contractor_"))
    A("Plus %d route and %d contractor fixed effects (not listed: naming every route "
      "with its productivity would publish the shape of the operation)." % (n_route, n_contr))
    A("")
    A("**Significant at p<0.05: %d of %d features.** Max VIF %.2f (nothing above 10, "
      "so coefficients are separately identified). Condition number %s."
      % (len(sig.get("significant_features", [])), sig.get("n_features", 0),
         sig.get("max_vif", 0), f"{sig.get('condition_number', 0):,.0f}"))
    A("")

    # ── how to read it ──────────────────────────────────────────────────────
    A("### Reading the significant effects")
    A("")
    wb = coefs.get("weighbridges_open", {})
    tp = coefs.get("trucks_per_path", {})
    rm = coefs.get("rainfall_missing", {})
    if wb:
        A("- **Weighbridges open %+.3f** — each additional open weighbridge is worth "
          "about %.3f extra trips per truck per shift. The clearest operational lever "
          "in the model." % (wb["coef"], wb["coef"]))
    if tp:
        A("- **Shared-road congestion %+.5f** — the sign is *positive*, which is not "
          "what a congestion story predicts. Busy roads are busy because the routes are "
          "productive; this is association, not a causal claim that adding trucks helps."
          % tp["coef"])
    if rm:
        A("- **Rainfall missing %+.3f** — rows after the gauge outage read higher. This "
          "is a data-quality marker, not weather: it separates imputed rows from "
          "measured ones so the model does not treat a guess as a reading." % rm["coef"])
    A("")

    # ── residuals ───────────────────────────────────────────────────────────
    A("## Residual diagnostics — the Phase 4 decision")
    A("")
    A("| Check | Result |")
    A("|---|---|")
    A("| Heteroscedastic | **%s** (corr \\|residual\\| vs fitted = %.3f) |"
      % ("yes" if res.get("heteroscedastic_flag") else "no",
         res.get("heteroscedasticity_corr", 0)))
    A("| Non-linear features flagged | %s |"
      % (", ".join(res.get("nonlinear_features", [])) or "none"))
    A("| Residual mean / std | %.4f / %.3f |"
      % (res.get("residual_mean", 0), res.get("residual_std", 0)))
    A("")
    if res.get("heteroscedastic_flag"):
        A("Error grows with the size of the prediction, so a constant-variance linear")
        A("model is the wrong shape. But **no single feature shows curvature**, and every")
        A("fitted model already loses to a lookup table. More months of data will buy more")
        A("than a more flexible model would.")
        A("")

    # ── excluded ────────────────────────------------------------------------
    fm = meta.get("feature_meta", {})
    A("## Excluded on purpose")
    A("")
    A("### Target leakage (verified, not assumed)")
    A("")
    A("```")
    A("wmt_per_shift == target x payload_t x trucks_dt    max abs error 0.000000")
    A("trips / trucks_dt == target                        max abs error < 1e-8")
    A("```")
    A("")
    A("Both are exact algebraic restatements of the target: including either drives R²")
    A("toward 1.0 while making the model useless, because at planning time nobody knows")
    A("the trips or the tonnage — that is the question being asked. `cycle_time_min` is")
    A("excluded too: it is derived from weighbridge timestamps *after* the shift ran.")
    A("")
    for note in fm.get("dropped_redundant", []):
        A("- Dropped: %s" % note)
    A("")
    A("### Rainfall imputation")
    A("")
    A("%s. Gauges stopped reporting **%s**; %s rows are imputed with a seasonal mean and "
      "flagged via `rainfall_missing`, so the model can tell a guess from a measurement."
      % (fm.get("rain_imputation", "seasonal mean + missing flag"),
         fm.get("rain_outage_from", "?"), f"{fm.get('rain_imputed_rows', 0):,}"))
    A("")

    # ── what's missing ──────────────────────────────────────────────────────
    A("## Features the roadmap wants that the data cannot support")
    A("")
    A("Do not fabricate these. Each needs a new data source.")
    A("")
    A("| Feature | Blocker |")
    A("|---|---|")
    A("| Road grade | No survey/DEM per path. Needs road geometry or an elevation raster. |")
    A("| Operator experience | No operator ID on haul records. Needs FMS operator assignment + hours. |")
    A("| Truck type / capacity | `trucks_dt` is a count, not a spec. Needs a truck master table. |")
    A("| Cycle-time components | Only the aggregate is derivable, and only post-hoc. Needs geofence timestamps. |")
    A("| Weather beyond rain | No temperature/humidity/visibility. External API, low priority while gauges are down. |")
    A("")
    A("---")
    A("")
    A("Reproduce: `python train_model.py` (needs VPN for the DB; falls back to fixtures "
      "otherwise), then `python scripts/publish_findings.py`.")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    md = build()
    if not md:
        print("no artifacts in data/ — run `python train_model.py` first", file=sys.stderr)
        raise SystemExit(1)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(md)
    print("wrote %s (%d lines)" % (os.path.relpath(OUT, BASE), md.count("\n")))
